//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.NodosTelefonia
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nodos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NodosTelefonia";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NodosTelefoniaDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NodosTelefoniaCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NodosTelefoniaExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NodosTelefoniaCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNodosTelefoniaExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NodosTelefoniaCommandSetId), 0x0001);
	
		// Package identifier
		public const string NodosTelefoniaPackageId = "28c459e7-477d-4777-a7d1-77359344453e";
		
		// Editor factory identifier
		public const string NodosTelefoniaEditorFactoryId = "48b124cd-4084-44c7-a6c9-9f141550efae";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NodosTelefoniaModelExplorerToolWindowId = "23bbd8f3-9782-4e5c-ab82-086bcdb11ba9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace IPS.NodosTelefonia
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NodosTelefoniaCommandSetId = "f1b0e0d8-8fc3-4d6b-8f57-37a8c2618c05";
	}
}